### ISSUE TITLE
??? inflating kill count

### ISSUE THREAD

**Issue by kekvaze** [Axema/Secronom-Zombies#3]
hey uh not sure if this is really an issue or even something you can mess with rather then base game or if the cdda launcher has an outdated version or something but a zombie attacked a ??? which caused it to gravitational collapse spawning a bunch of carrion that started attacking the ??? causing more gravitational collapses killing and spawning more carrion but its being added to my kill count for some reason
![Capture](https://user-images.githubusercontent.com/56379754/67071448-69152700-f137-11e9-9d0f-4f183e472f3a.PNG)
only a problem/exploit cause I have the stats through kills mod so its giving me free stat points

**Comment by Axema** [comment]
Oh... Because spellcasting is registered as player's.
There are tons of monsters with spells intended to kill other creatures and this is unavoidable :frowning_face:
(I will try to make this as an issue)

??? seems to be bugged (it should die in one collapse) and its on-death monster spawnrate has to be lower than 15~.

**Comment by Axema** [comment]
It is (Issued)[https://github.com/CleverRaven/Cataclysm-DDA/issues/34858] 👍

**Comment by kekvaze** [comment]
cool thanks so does this mean the one in the mod in the launcher is outdated then or does it just grab from github and should be latest
